### ISSUE TITLE
Depends on Node v12 but GitHub requires at least Node v20

### ISSUE THREAD

**Issue by LinusSee** [sparksp/elm-review-action#49]
Github Actions require at least node v20, so when running the elm-review-action the following warnings are shown:

- The following actions uses node12 which is deprecated and will be forced to run on node16: sparksp/elm-review-action@v1.
- Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: sparksp/elm-review-action@v1.

**Comment by LinusSee** [comment]
If you don't mind, I would love to create a Fork/PR for this, since I haven't done it for any repository other than my own before and this seems like a good issue to give it a shot (assuming it is just updating the node version in the `action.yaml`)

**Comment by sparksp** [comment]
You are quite welcome to give a PR a go

**Comment by LinusSee** [comment]
Thank you for the opportunity :)

**Comment by sparksp** [comment]
Thanks for all this @LinusSee - I have updated dependencies and release this as `v1.1.0`. If you are using `@v1` then it should just work.

**Comment by LinusSee** [comment]
Yep, worked like a charm, thank you :)
